#spring:
#  application:
#    name: demo-cucumber
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/cucumber_db
#    username: "${POSTGRES_USERNAME}"
#    password: "${POSTGRES_PASSWORD}"
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#      show-sql: true
#    database: postgresql
#
#server:
#  port: 8081
